// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfkuwlduckspyygjacon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhma3V3bGR1Y2tzcHl5Z2phY29uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwOTM1NDgsImV4cCI6MjA1ODY2OTU0OH0.YP5EQdWJzv6CbNXOj1y6I0qSaBXzHOZh_D8Kio9h-qc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);